### ISSUE TITLE
Wording change suggestion to solve failure explanations

### ISSUE THREAD

**Issue by deivid-rodriguez** [jhawthorn/pub_grub#18]
While porting Bundler to use pub_grub, it was noticed by @indirect that maybe pub_grub error messages could be improved by avoiding to mention the word "forbidden", the rationale being that forbidden is usually authorization related:

> I think the reason “forbidden” can possibly be a little misleading is because we often use that word around permissions or authorization—so it might give the impressions that the user could use that gem if only they had the right permission. Instead, we are trying to say “we can’t do that because it is a logical impossibility” which has a different feel.

So instead of

> foo >= 2.0 is forbidden

or

> every version of foo is forbidden

We could say

> foo >= 2.0 cannot be used

or

> foo cannot be used

If there's consensus that this would be an improvement, maybe it can be changed here.

**Comment by jhawthorn** [comment]
I agree your wording reads much better

**Comment by jhawthorn** [comment]
Fixed by #24
